name: 'dw_fluxo_caixa'
version: '1.0.0'


profile: 'dw_fluxo_caixa'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"


models:
  dw_fluxo_caixa:
    
    staging: 
      +schema: staging
      +materialized: view
    
    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table  